{
  echo "<?php"
  echo "require './vendor/autoload.php';"
  echo ""
  echo "use Facebook\\WebDriver\\Chrome\\ChromeOptions;"
  echo "use Facebook\\WebDriver\\Remote\\DesiredCapabilities;"
  echo "use Facebook\\WebDriver\\Remote\\RemoteWebDriver;"
  echo "use Facebook\\WebDriver\\WebDriverBy;"
  echo "use Facebook\\WebDriver\\WebDriverExpectedCondition;"
  echo "use Facebook\\WebDriver\\Exception\\NoSuchElementException;"
  echo "use Facebook\\WebDriver\\Exception\\UnrecognizedExceptionException;"
  echo "use Facebook\\WebDriver\\Exception\\UnexpectedJavascriptException;"
  echo "use Facebook\\WebDriver\\Exception\\StaleElementReferenceException;"
  echo "use Facebook\\WebDriver\\Exception\\WebDriverCurlException;"
  echo ""
  echo "\$host = 'http://localhost:4444/wd/hub';"
  echo "\$options = new ChromeOptions();"
  echo "\$width  = 960;"
  echo "\$height = 1024;"
  echo "\$options->addArguments( [ \"window-size={\$width},{\$height}\" ] );"
  echo "\$capabilities = Facebook\\WebDriver\\Remote\\DesiredCapabilities::chrome();"
  echo "\$capabilities->setCapability(ChromeOptions::CAPABILITY, \$options);"
  echo "\$driver = Facebook\\WebDriver\\Remote\\RemoteWebDriver::create(\$host, \$capabilities);"
  echo ""
  echo ""
  echo "\$url = '$1';"
  echo "\$xpath_for_ajax = '$2';"
  echo "\$column_numbers_to_scrape = $3;"
  echo "\$titles = $4;"
  echo "\$xpath_of_a = '$6';"
  echo "\$xpaths_to_scrape_in_a_new_page = $7;"
#  echo "\$data = [];"
  echo "\$scraped_data = [];"
  echo "array_push(\$scraped_data, \$titles);"
  echo "\$hrefs = [];"
  echo ""
  echo ""
  echo "\$driver->get(\$url);"
  echo ""
  echo ""
  echo "if (\$xpath_for_ajax != 'null') {"
  echo "  \$ajax_btn = \$driver->findElement(WebDriverBy::xpath(\$xpath_for_ajax));"
  echo "  \$ajax_btn->click();"
  echo "}"
  echo ""
  echo "\$driver->wait()->until(WebDriverExpectedCondition::elementToBeClickable(WebDriverBy::tagName('td')));"
  echo "sleep(10);"
  echo ""
  echo "\$rows = $5;"
  # echo "\$tbody_trs = \$driver->findElements(WebDriverBy::xpath(\"//tbody/tr\"));"
  # echo "\$rows = count(\$tbody_trs);"
  echo ""
  echo ""
  echo "for (\$i = 1; \$i <= \$rows; \$i++) {"
  echo "  \$scraped_row_data = [];"
  echo ""
  echo "  for (\$j=0; \$j < count(\$column_numbers_to_scrape); \$j++) {"
  echo "    try {"
  echo "      \$Is_this_td_row = 'y';"
  echo "      \$td = \$driver->findElement(WebDriverBy::xpath(\"//tbody/tr[\$i]/td[\$column_numbers_to_scrape[\$j]]\")); //Element"
  echo "      array_push(\$scraped_row_data, \$td->getText());"
  echo "    }catch (NoSuchElementException \$e) {"
  echo "      \$Is_this_td_row = 'n';"
  echo "      break;"
  echo "    }"
  echo "  }"
  echo ""
  echo "  if (\$Is_this_td_row == 'y') {"
  echo "    if (\$xpath_of_a != 'null') {"
  echo "      \$preg_xpath_of_a = preg_replace(\"/tr\\[[0-9]+\\]/\", \"tr[\$i]\", \$xpath_of_a);"
  echo "      \$a = \$driver->findElement(WebDriverBy::xpath(\$preg_xpath_of_a));"
  echo "      \$href = \$a->getAttribute('href');"
  echo "      array_push(\$hrefs, \$href);"
  echo "    }"
  echo ""
  echo "    array_push(\$scraped_data, \$scraped_row_data);"
  echo "  }"
  echo "}"
  echo ""
  echo ""
  # echo "for (\$i = 0; \$i < count(\$scraped_data); \$i++) {"
  # echo "  if (\$i == 0) {"
  # echo "    array_unshift(\$scraped_data[\$i], 'id');"
  # echo "  } else {"
  # echo "    array_unshift(\$scraped_data[\$i], \$i);"
  # echo "  }"
  # echo "}"
  echo ""
  echo "echo json_encode(\$scraped_data);"
  echo "//echo json_encode(\$hrefs);"
  echo "//echo json_encode(\$xpaths_to_scrape_in_a_new_page);"
  echo "\$driver->close();"
  echo ""
  echo ""
} > scraping.php

if [ $8 -gt 0 ]; then
  {
    echo "for (\$i = 1; \$i <= count(\$hrefs); \$i++) {"
    echo "  \${'href_runtime'.\$i} = new \parallel\Runtime();"
    echo "}"
    echo ""
  } >> scraping.php
fi

for i in `seq $8`
do
  {
    echo "\$href_future${i} = \$href_runtime${i}->run(function(\$href, \$xpaths_to_scrape_in_a_new_page){"
    echo "  \$html = file_get_contents(\$href);"
    echo "  \$dom = new DOMDocument();"
    echo "  @\$dom->loadHTML(\$html);"
    echo "  \$xpath = new DOMXPath(\$dom);"
    echo "  \$data = [];"
    echo ""
    echo "  for (\$i = 0; \$i < count(\$xpaths_to_scrape_in_a_new_page); \$i++) {"
    echo "    \$value = \$xpath->query(\$xpaths_to_scrape_in_a_new_page[\$i])->item(0)->nodeValue;"
    echo "    array_push(\$data, \$value);"
    echo "  }"
    echo ""
    echo "  return \$data;"
    echo "}, array(\$hrefs[$(echo $(($i - 1)))], \$xpaths_to_scrape_in_a_new_page));"
    echo ""
  } >> scraping.php
done

if [ $8 -gt 0 ]; then
  {
    echo "for (\$i = 1; \$i < count(\$scraped_data); \$i++) {"
    echo "  for (\$j = 0; \$j < count(\${'href_future'.\$i}->value()); \$j++) {"
    echo "    array_push(\$scraped_data[\$i], \${'href_future'.\$i}->value()[\$j]);"
    echo "  }"
    echo "}"
    echo ""
  } >> scraping.php
fi


{
  echo "for (\$i = 0; \$i < count(\$scraped_data); \$i++) {"
  echo "  if (\$i == 0) {"
  echo "    array_unshift(\$scraped_data[\$i], 'id');"
  echo "  } else {"
  echo "    array_unshift(\$scraped_data[\$i], \$i);"
  echo "  }"
  echo "}"
  echo "?>"
  echo ""
} >> scraping.php

{
  echo "<script type=\"text/javascript\">"
  echo "  const data = JSON.parse('<?php echo json_encode(\$scraped_data); ?>');"
#  echo "  console.log(data);"
  echo "</script>"
  echo ""
  echo ""
} >> scraping.php

{
  echo "<!doctype html>"
  echo "<html lang=\"en\">"
  echo "  <head>"
  echo "    <meta charset=\"utf-8\">"
  echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  echo "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">"
  echo "    <link rel=\"stylesheet\" href=\"http://localhost:81/ssr/index.css\">"
  echo "  </head>"
  echo "  <body class=\"m-1\">"
  echo "    <div id=\"result_table_section\"></div>"
  echo ""
  echo "    <form class=\"mb-5\" id=\"chart_form\">"
  echo "      <div class=\"form-check\">"
  echo "        <input class=\"form-check-input\" type=\"radio\" name=\"condition\" id=\"group_by_a_column_radio\">group by a column"
  echo "        <div id=\"group_by_a_column_section\"></div>"
  echo "      </div>"
  echo ""
  echo "      <div class=\"form-check\">"
  echo "        <input class=\"form-check-input\" type=\"radio\" name=\"condition\" id=\"range_radio\">range"
  echo "        <div id=\"range_section\"></div>"
  echo "      </div>"
  echo ""
  echo "      <div class=\"form-check\">"
  echo "        <input class=\"form-check-input\" type=\"radio\" name=\"condition\" id=\"keyword_radio\">keyword"
  echo "        <div id=\"keyword_section\"></div>"
  echo "      </div>"
  echo ""
  echo "      <button type=\"button\" class=\"btn btn-primary\" id=\"see_chart_btn\">see chart</button>"
  echo "    </form>"
  echo ""
  echo "    <div id=\"chart_section\"></div>"
  echo ""
  echo "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>"
  echo "    <script type=\"text/javascript\" src=\"http://localhost:81/ssr/paginathing.js\"></script>"
  echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js\"></script>"
  echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js\"></script>"
  echo "    <script src=\"http://localhost:81/ssr/background_colors.js\"></script>"
  echo "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ\" crossorigin=\"anonymous\"></script>"
  echo "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js\" integrity=\"sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/\" crossorigin=\"anonymous\"></script>"
  echo "    <script src=\"http://localhost:81/ssr/list_chart.js\"></script>"
  echo "  </body>"
  echo "</html>"
} >> scraping.php
